### ISSUE TITLE
getting error in Heroku logs

### ISSUE THREAD

**Issue by mjwebhacks** [Ns-Bots/TG-File-Store#27]
Bot is working fine but getting an error after some time in Heroku logs.

2022-06-24T03:31:16.798962+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2022-06-24T03:31:16.798962+00:00 app[worker.1]:
2022-06-24T03:31:16.798962+00:00 app[worker.1]: Traceback (most recent call last):
2022-06-24T03:31:16.798963+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-06-24T03:31:16.798963+00:00 app[worker.1]: await handler.callback(self.client, *args)
2022-06-24T03:31:16.798963+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pyromod/listen/listen.py", line 93, in resolve_listener
2022-06-24T03:31:16.798964+00:00 app[worker.1]: await self.user_callback(client, message, *args)
2022-06-24T03:31:16.798964+00:00 app[worker.1]: File "/app/plugins/Forcesub.py", line 23, in forcesub
2022-06-24T03:31:16.798965+00:00 app[worker.1]: chat_id, msg_id = decoded_data.split('_')
2022-06-24T03:31:16.798965+00:00 app[worker.1]: ValueError: too many values to unpack (expected 2)

**Comment by mjwebhacks** [comment]
issue resolved
